version: 2.1
jobs:
  install-dependencies:
    docker:
      - image: circleci/node:10.13.0
      - image: circleci/mongo:4.0.5
    steps:
      - checkout
      - run:
          name: npm install
          command: |
            npm install
  test:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - run:
          name: npm test
          command: |
            npm test
workflows:
 version: 2
 Example_Workflow:
   jobs:
     - install-dependencies
     - test:
        requires:
          - install-dependencies

