version: 2.1
jobs:
  MongoDB:
    docker:
      - image: circleci/mongo:4.0.5
    steps:
      - run:
          name: Start MongoDB
          command: |
            mongod --port 27017
  Node:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - run:
          name: Show Node version
          command: |
            node -v
      - run:
          name: Install package
          command: |
            npm install
workflows:
 version: 2
 Example_Workflow:
   jobs:
     - MongoDB