version: 2.1
orbs:
  node: circleci/node@2.0.2
jobs:
  build-and-test:
    docker:
      - image: circleci/mongo:4.0.5
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
  matrix-tests:
    jobs:
      - node/test:
          version: 10.13.0
      - node/test:
          version: 10.13.0
      - node/test:
          version: 10.13.0
  build-and-test:
    jobs:
      - build-and-test
