version: 2.1
orbs:
  node: circleci/node@2.0.2
jobs:
  build-and-test:
    docker:
      - image: circleci/mongo:4.0.5-node
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test
