version: 2.1
jobs:
  MongoDB:
    docker:
      - image: circleci/mongo:4.0.5
    steps:
      - run:
          name: Show version MongoDB
          command: |
            mongod --version
workflows:
 version: 2
 Example_Workflow:
   jobs:
     - MongoDB