version: 2.1
defaults: &defaults
  working_directory: ~/repo
  docker:
   - image: circleci/node:10.13.0
jobs:
  Node:
    <<: *defaults
    steps:
      - run:
          name: Show Node version
          command: |
            node -v
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install package
          command: |
            npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  Test:
    docker:
      - image: circleci/mongo:4.0.5
    steps:
      - checkout
      - run:
          name: Test
          command: |
            npm test
          
workflows:
 version: 2
 Example_Workflow:
   jobs:
     - Node
     - Test:
          requires:
            - Node